// =========================================================
// NetMine AI — Reports Page
// Live Analytical Summaries & Live Data Export
// =========================================================
import { useState, useEffect } from "react";
import { Download, FileText, Calendar, BarChart2, Radio, CheckCircle } from "lucide-react";
import Topbar from "../components/layout/Topbar";
import { getApiUrl } from "../services/api";

function formatBytes(b: number) {
  if (!b || isNaN(b)) return "0 B";
  if (b > 1e9) return `${(b / 1e9).toFixed(2)} GB`;
  if (b > 1e6) return `${(b / 1e6).toFixed(1)} MB`;
  if (b > 1e3) return `${(b / 1e3).toFixed(1)} KB`;
  return `${b} B`;
}

const API = getApiUrl();

export default function Reports() {
  const [exporting, setExporting] = useState<string | null>(null);
  const [anomalies, setAnomalies] = useState<any[]>([]);
  const [flows, setFlows] = useState<any[]>([]);
  const [devices, setDevices] = useState<any[]>([]);

  useEffect(() => {
    // Fetch live anomalies
    fetch(`${API}/api/anomalies?source=live`)
      .then(r => r.json())
      .then(d => { if (d && d.anomalies) setAnomalies(d.anomalies); })
      .catch(() => {});

    // Fetch live flows
    fetch(`${API}/api/capture/flows?limit=100`)
      .then(r => r.json())
      .then(d => { if (d && d.flows) setFlows(d.flows); })
      .catch(() => {});

    // Fetch live devices
    fetch(`${API}/api/devices`)
      .then(r => r.json())
      .then(d => { if (d && d.devices) setDevices(d.devices); })
      .catch(() => {});
  }, []);

  // Compute live attack type breakdown
  const attackCounts = anomalies.reduce((acc: Record<string, number>, a: any) => {
    acc[a.type] = (acc[a.type] ?? 0) + 1;
    return acc;
  }, {});

  // Compute live top talkers from live flows & devices
  const talkerMap: Record<string, number> = {};
  flows.forEach((f: any) => {
    const ip = f.src_ip || f.srcIp;
    if (ip) talkerMap[ip] = (talkerMap[ip] ?? 0) + (f.bytes || 0);
  });
  devices.forEach((d: any) => {
    if (d.ip) talkerMap[d.ip] = Math.max(talkerMap[d.ip] ?? 0, d.total_bytes ?? d.totalBytes ?? 0);
  });

  const topTalkers = Object.entries(talkerMap)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .map(([ip, bytes]) => ({ ip, bytes }));

  function handleExport(reportId: string) {
    setExporting(reportId);
    try {
      const reportPayload = {
        title: `NetMine AI - ${reportId.toUpperCase()} Report`,
        timestamp: new Date().toISOString(),
        system: "NetMine AI Real-Time Network Security & Anomaly Engine",
        data_source: "100% Live Capture",
        summary: {
          total_anomalies: anomalies.length,
          total_devices: devices.length,
          recent_flows: flows.length,
        },
        attack_distribution: attackCounts,
        top_talkers: topTalkers,
        devices: devices.slice(0, 10),
        recent_threats: anomalies.slice(0, 10),
      };

      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(reportPayload, null, 2));
      const downloadAnchor = document.createElement("a");
      downloadAnchor.setAttribute("href", dataStr);
      downloadAnchor.setAttribute("download", `netmine-${reportId}-report-${Date.now()}.json`);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      downloadAnchor.remove();
    } catch (err) {
      console.error("Export error:", err);
    } finally {
      setTimeout(() => setExporting(null), 1000);
    }
  }

  const REPORTS = [
    { id: "daily",   title: "Live Security Summary", desc: "Real-time traffic overview, active protocol analysis, and threat telemetry.", icon: <Calendar size={18} /> },
    { id: "threats", title: "Live Threat Report",    desc: "Active threat detections, port scan alerts, and flagged suspicious IPs.", icon: <BarChart2 size={18} /> },
    { id: "devices", title: "Device Inventory Report", desc: "Network host registry, observed IP addresses, and bandwidth breakdown.", icon: <FileText size={18} /> },
    { id: "flows",   title: "Flow Audit Export",      desc: "Detailed record of recently classified bidirectional packet flows.", icon: <Download size={18} /> },
  ];

  return (
    <>
      <Topbar title="Reports" subtitle="Live analytical summaries and data exports" />
      <div className="page-content fade-in-up">

        <div className="page-header">
          <div className="page-header-left">
            <h1 className="page-header-title">Reports & Exports</h1>
            <p className="page-header-subtitle">
              Export live telemetry and threat intelligence generated by the live capture engine
            </p>
          </div>
        </div>

        {/* Report cards */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 20 }}>
          {REPORTS.map(r => (
            <div className="card" key={r.id} style={{ position: "relative", overflow: "hidden" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <div style={{
                    width: 36, height: 36, borderRadius: 8,
                    background: "rgba(59,130,246,0.1)", border: "1px solid rgba(59,130,246,0.2)",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    color: "var(--color-accent-primary)",
                  }}>
                    {r.icon}
                  </div>
                  <h3 style={{ fontWeight: 700, margin: 0 }}>{r.title}</h3>
                </div>
                <button
                  onClick={() => handleExport(r.id)}
                  style={{
                    display: "flex", alignItems: "center", gap: 6,
                    background: exporting === r.id ? "var(--color-success)" : "var(--color-accent-primary)",
                    color: "#fff", border: "none", borderRadius: 8, padding: "6px 14px",
                    fontSize: "0.78rem", fontWeight: 600, cursor: "pointer",
                    transition: "background 0.2s",
                  }}
                >
                  <Download size={13} />
                  {exporting === r.id ? "Downloaded" : "Export JSON"}
                </button>
              </div>
              <p style={{ fontSize: "0.82rem", color: "var(--color-text-muted)", lineHeight: 1.5, margin: 0 }}>
                {r.desc}
              </p>
            </div>
          ))}
        </div>

        {/* Attack type breakdown */}
        <div className="card" style={{ marginBottom: 16 }}>
          <div className="card-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span className="card-title">Live Attack Type Breakdown</span>
            <span className="live-badge" style={{ display: "inline-flex", alignItems: "center", gap: 4 }}>
              <span className="live-dot" /> LIVE THREATS
            </span>
          </div>
          {Object.keys(attackCounts).length === 0 ? (
            <div style={{ padding: "32px 16px", textAlign: "center", color: "var(--color-text-muted)", fontSize: "0.85rem" }}>
              No attacks detected in current live session. The network is clean.
            </div>
          ) : (
            <div style={{ overflowX: "auto" }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Attack Type</th>
                    <th>Count</th>
                    <th>Share</th>
                    <th>Distribution</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(attackCounts).map(([type, count]) => {
                    const pct = (count / (anomalies.length || 1)) * 100;
                    return (
                      <tr key={type}>
                        <td style={{ fontWeight: 600, color: "var(--color-text-primary)" }}>{type}</td>
                        <td style={{ fontFamily: '"JetBrains Mono",monospace' }}>{count}</td>
                        <td style={{ fontFamily: '"JetBrains Mono",monospace' }}>
                          {pct.toFixed(0)}%
                        </td>
                        <td>
                          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                            <div style={{ flex: 1, height: 6, borderRadius: 3, background: "var(--color-bg-hover)" }}>
                              <div style={{
                                width: `${pct}%`,
                                height: "100%", borderRadius: 3,
                                background: "var(--color-accent-primary)",
                              }} />
                            </div>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Top talkers */}
        <div className="card">
          <div className="card-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span className="card-title">Live Top Talkers (by traffic volume)</span>
            <span className="live-badge" style={{ display: "inline-flex", alignItems: "center", gap: 4 }}>
              <span className="live-dot" /> LIVE TRAFFIC
            </span>
          </div>
          {topTalkers.length === 0 ? (
            <div style={{ padding: "32px 16px", textAlign: "center", color: "var(--color-text-muted)", fontSize: "0.85rem" }}>
              No active talkers observed yet. Start live capture to monitor hosts.
            </div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>IP Address</th>
                  <th>Observed Traffic</th>
                </tr>
              </thead>
              <tbody>
                {topTalkers.map((t, i) => (
                  <tr key={t.ip}>
                    <td style={{ color: "var(--color-text-muted)", fontFamily: '"JetBrains Mono",monospace' }}>{i + 1}</td>
                    <td><span className="ip-text" style={{ fontWeight: 600 }}>{t.ip}</span></td>
                    <td style={{ fontFamily: '"JetBrains Mono",monospace', color: "var(--color-accent-secondary)" }}>
                      {formatBytes(t.bytes)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

      </div>
    </>
  );
}
